
const WikipediaMain = () => {
  return (
    <main>
        <h1>FC Barcelona</h1>
        <section>
            <p>Futbol Club Barcelona (Catalan pronunciation: [fubˈbɔl ˈklub bəɾsəˈlonə] ⓘ), commonly known as Barcelona and familiarly as Barça ([ˈbaɾsə]), is a professional football club based in Barcelona, Catalonia, Spain, that competes in La Liga, the top flight of Spanish football.

Founded in 1899 by a group of Swiss, Catalan, German, and English footballers led by Joan Gamper, the club has become a symbol of Catalan culture and Catalanism, hence the motto "Més que un club" ("More than a club").[2] Unlike many other football clubs, the supporters own and operate Barcelona. It is the third-most valuable football club in the world, worth $5.51 billion, and the world's fourth richest football club in terms of revenue, with an annual turnover of €800.1 million.[3][4] The official Barcelona anthem is the "Cant del Barça", written by Jaume Picas and Josep Maria Espinàs.[5] Barcelona traditionally play in dark shades of blue and garnet stripes, hence nicknamed Blaugrana.

Domestically, Barcelona has won a record 77 trophies: 27 La Liga, 31 Copa del Rey, 14 Supercopa de España, three Copa Eva Duarte, and two Copa de la Liga titles, as well as being the record holder for the latter four competitions. In international club football, the club has won 22 European and worldwide titles: five UEFA Champions League titles, a record four UEFA Cup Winners' Cups, a joint record five UEFA Super Cups, a record three Inter-Cities Fairs Cups, a joint record two Latin Cups, and three FIFA Club World Cups.[6][7][8] Barcelona was ranked first in the International Federation of Football History & Statistics Club World Ranking for 1997, 2009, 2011, 2012, and 2015, and occupies the ninth position on the UEFA club rankings as of May 2023.[9][10][11] The club has a long-standing rivalry with Real Madrid, and matches between the two teams are referred to as El Clásico.

Barcelona is one of the most widely supported teams in the world, and the club has one of the largest social media following in the world among sports teams.[12][13] Barcelona players have won a joint record twelve Ballon d'Or awards, with recipients including Johan Cruyff, as well as a record six FIFA World Player of the Year awards, with winners including Romário, Ronaldo, Rivaldo, and Ronaldinho. In 2010, three players who came through the club's youth academy (Lionel Messi, Andrés Iniesta and Xavi) were chosen as the three best players in the world in the FIFA Ballon d'Or awards, an unprecedented feat for players from the same football academy.[14][15] Additionally, players representing the club have won a record eight European Golden Shoe awards.[16]

Barcelona is one of three founding members of the Primera División that have never been relegated from the top division since its inception in 1929, along with Athletic Bilbao and Real Madrid.[17][18] In 2009, Barcelona became the first Spanish club to win the continental treble consisting of La Liga, Copa del Rey and the UEFA Champions League, and also became the first European football club to win six out of six competitions in a single year, by also winning the Spanish Super Cup, UEFA Super Cup and FIFA Club World Cup.[19] In 2011, the club became European champions again, winning five trophies.[20] This Barcelona team, which won fourteen trophies in just four years under Pep Guardiola, is considered by some in the sport to be the greatest team of all time.[21][22][23] By winning their fifth Champions League trophy in 2015 under Luis Enrique, Barcelona became the first European football club in history to achieve the continental treble twice.</p>
        </section>
        <section>
            <p>On 22 October 1899, Swiss Hans Gamper placed an advertisement in Los Deportes declaring his wish to form a football club; a positive response resulted in a meeting at the Gimnasio Solé on 29 November. Eleven players attended – Walter Wild (the first president of the club), Luis de Ossó, Bartomeu Terradas, Otto Kunzle, Otto Maier, Enric Ducal, Pere Cabot, Carles Pujol, Josep Llobet, John Parsons, and William Parsons – and Foot-Ball Club Barcelona was born.[26][27]
A formation of FC Barcelona in 1903
FC Barcelona had a successful start in regional and national cups, competing in the Campionat de Catalunya and the Copa del Rey. In 1901, the club participated in the first football competition played on the Iberian Peninsula, the Copa Macaya, narrowly losing to Hispania AC, but in the following year, Barça won the tournament, the club's first-ever piece of silverware,[28] and then participated in the first Copa del Rey, losing 1–2 to Bizcaya (a combination of players from Athletic Club and Bilbao FC) in the final.[29] In 1908, Hans Gamper – now known as Joan Gamper – became club president in a desperate attempt to save Barcelona from extinction, finding the club struggling not just on the pitch, but also financially and socially, after not winning a competition since the Campionat de Catalunya in 1905. He said in a meeting, "Barcelona cannot die and must not die. If there is nobody who is going to try, then I will assume the responsibility of running the club from now on."[30] Club president on five separate occasions between 1908 and 1925, he spent 25 years in total at the helm. One of his main achievements was ensuring Barça acquire its own stadium and thus generate a stable income.[31]

On 14 March 1909, the team moved into the Camp de la Indústria, a stadium with a capacity of 8,000. To celebrate their new surroundings, the club conducted a logo contest the following year. Carles Comamala won the contest, and his suggestion became the crest that the club still wears – with some minor changes – as of the present day.[32]

The stadium is regarded as the main element that helped the club grow in the 1910s and become a dominant team,[33] winning three successive Campionats de Catalunya between 1909 and 1911, three Copa del del Rey in four years between 1910 and 1913, and four successive Pyrenees Cup between the inaugural year in 1910 and 1913, which was one of the earliest international club cups in Europe since it consisted of the best teams of Languedoc, Midi and Aquitaine (Southern France), the Basque Country and Catalonia; all were former members of the Marca Hispanica region. The contest was the most prestigious in that era.[34] Notable figures of Barça's first great team include Carles Comamala, Alfredo Massana, Amechazurra, Paco Bru, and Jack Greenwell.[35] The latter became the club's first full-time coach in 1917.</p>
        </section>
        <section>
            <p>In 1978, Josep Lluís Núñez became the first elected president of FC Barcelona, and, since then, the members of Barcelona have elected the club president. The process of electing a president of FC Barcelona was closely tied to Spain's transition to democracy in 1974 and the end of Franco's dictatorship. The new president's main objective was to develop Barcelona into a world-class club by giving it stability both on and off the pitch. His presidency was to last for 22 years, and it deeply affected the image of Barcelona, as Núñez held to a strict policy regarding wages and discipline, letting go of such players as Diego Maradona, Romário and Ronaldo rather than meeting their demands.[72][73]

On 16 May 1979, the club won its first European Cup Winners' Cup by beating Fortuna Düsseldorf 4–3 in Basel in a final watched by more than 30,000 travelling blaugrana fans. The same year, Núñez began to invest in the club's youth programme by converting La Masia into a dormitory for young academy players from abroad. The name of the dormitory would later become synonymous with the youth programme of Barcelona.[74]

In June 1982, Diego Maradona was signed for a world record fee of £5 million from Boca Juniors.[75] In the following season, under coach César Luis Menotti, Barcelona won the Copa del Rey, beating Real Madrid. Maradona's time with Barcelona, however, was short-lived and he soon left for Napoli. At the start of the 1984–85 season, Terry Venables was hired as manager and he won La Liga with noteworthy displays by German midfielder Bernd Schuster. The next season, he took the team to their second European Cup final, only to lose on penalties to Steaua București during a dramatic evening in Seville.[72]

Around this time, tensions began to arise between what was perceived as president Núñez's dictatorial rule and the nationalistic support group, Boixos Nois. The group, identified with a left-wing separatism, repeatedly demanded the resignation of Núñez and openly defied him through chants and banners at matches. At the same time, Barcelona experienced an eruption in skinheads, who often identified with a right-wing separatism. The skinheads slowly transferred the Boixos Nois' ideology from liberalism to fascism, which caused division within the group and a sudden support for Núñez's presidency.[76] Inspired by British hooligans, the remaining Boixos Nois became violent, causing havoc leading to large-scale arrests.[77]

After the 1986 FIFA World Cup, Barcelona signed the English top scorer Gary Lineker, along with goalkeeper Andoni Zubizarreta, but the team could not achieve success, as Schuster was excluded from the team. Terry Venables was subsequently fired at the beginning of the 1987–88 season and replaced with Luis Aragonés. The season finished with the players rebelling against president Núñez, in an event known as the Hesperia mutiny, and a 1–0 victory in the Copa del Rey final against Real Sociedad</p>
        </section>
    </main>
  )
}

export default WikipediaMain